/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditoriaIdRouteImport } from './routes/auditoria.$id'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaIdRoute = AuditoriaIdRouteImport.update({
  id: '/auditoria/$id',
  path: '/auditoria/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/login': typeof LoginRoute
  '/workspace': typeof WorkspaceRoute
  '/auditoria/$id': typeof AuditoriaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/login': typeof LoginRoute
  '/workspace': typeof WorkspaceRoute
  '/auditoria/$id': typeof AuditoriaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/conta': typeof ContaRoute
  '/login': typeof LoginRoute
  '/workspace': typeof WorkspaceRoute
  '/auditoria/$id': typeof AuditoriaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/conta' | '/login' | '/workspace' | '/auditoria/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/conta' | '/login' | '/workspace' | '/auditoria/$id'
  id: '__root__' | '/' | '/conta' | '/login' | '/workspace' | '/auditoria/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContaRoute: typeof ContaRoute
  LoginRoute: typeof LoginRoute
  WorkspaceRoute: typeof WorkspaceRoute
  AuditoriaIdRoute: typeof AuditoriaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria/$id': {
      id: '/auditoria/$id'
      path: '/auditoria/$id'
      fullPath: '/auditoria/$id'
      preLoaderRoute: typeof AuditoriaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContaRoute: ContaRoute,
  LoginRoute: LoginRoute,
  WorkspaceRoute: WorkspaceRoute,
  AuditoriaIdRoute: AuditoriaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
