/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as UtmsRouteImport } from './routes/utms'
import { Route as TurmasRouteImport } from './routes/turmas'
import { Route as ProprietariosRouteImport } from './routes/proprietarios'
import { Route as PacotesRouteImport } from './routes/pacotes'
import { Route as OrigemRouteImport } from './routes/origem'
import { Route as ModeloRouteImport } from './routes/modelo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GeografiaRouteImport } from './routes/geografia'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CanaisRouteImport } from './routes/canais'
import { Route as AuditoriaRouteImport } from './routes/auditoria'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspacesRouteImport } from './routes/app.workspaces'
import { Route as AdminImportRouteImport } from './routes/admin.import'
import { Route as AppWWidSourcesRouteImport } from './routes/app.w.$wid.sources'
import { Route as AppWWidModelRouteImport } from './routes/app.w.$wid.model'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const UtmsRoute = UtmsRouteImport.update({
  id: '/utms',
  path: '/utms',
  getParentRoute: () => rootRouteImport,
} as any)
const TurmasRoute = TurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProprietariosRoute = ProprietariosRouteImport.update({
  id: '/proprietarios',
  path: '/proprietarios',
  getParentRoute: () => rootRouteImport,
} as any)
const PacotesRoute = PacotesRouteImport.update({
  id: '/pacotes',
  path: '/pacotes',
  getParentRoute: () => rootRouteImport,
} as any)
const OrigemRoute = OrigemRouteImport.update({
  id: '/origem',
  path: '/origem',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeloRoute = ModeloRouteImport.update({
  id: '/modelo',
  path: '/modelo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GeografiaRoute = GeografiaRouteImport.update({
  id: '/geografia',
  path: '/geografia',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CanaisRoute = CanaisRouteImport.update({
  id: '/canais',
  path: '/canais',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspacesRoute = AppWorkspacesRouteImport.update({
  id: '/app/workspaces',
  path: '/app/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/admin/import',
  path: '/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWWidSourcesRoute = AppWWidSourcesRouteImport.update({
  id: '/app/w/$wid/sources',
  path: '/app/w/$wid/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWWidModelRoute = AppWWidModelRouteImport.update({
  id: '/app/w/$wid/model',
  path: '/app/w/$wid/model',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/canais': typeof CanaisRoute
  '/conta': typeof ContaRoute
  '/geografia': typeof GeografiaRoute
  '/login': typeof LoginRoute
  '/modelo': typeof ModeloRoute
  '/origem': typeof OrigemRoute
  '/pacotes': typeof PacotesRoute
  '/proprietarios': typeof ProprietariosRoute
  '/turmas': typeof TurmasRoute
  '/utms': typeof UtmsRoute
  '/vendas': typeof VendasRoute
  '/admin/import': typeof AdminImportRoute
  '/app/workspaces': typeof AppWorkspacesRoute
  '/app/w/$wid/model': typeof AppWWidModelRoute
  '/app/w/$wid/sources': typeof AppWWidSourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/canais': typeof CanaisRoute
  '/conta': typeof ContaRoute
  '/geografia': typeof GeografiaRoute
  '/login': typeof LoginRoute
  '/modelo': typeof ModeloRoute
  '/origem': typeof OrigemRoute
  '/pacotes': typeof PacotesRoute
  '/proprietarios': typeof ProprietariosRoute
  '/turmas': typeof TurmasRoute
  '/utms': typeof UtmsRoute
  '/vendas': typeof VendasRoute
  '/admin/import': typeof AdminImportRoute
  '/app/workspaces': typeof AppWorkspacesRoute
  '/app/w/$wid/model': typeof AppWWidModelRoute
  '/app/w/$wid/sources': typeof AppWWidSourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditoria': typeof AuditoriaRoute
  '/canais': typeof CanaisRoute
  '/conta': typeof ContaRoute
  '/geografia': typeof GeografiaRoute
  '/login': typeof LoginRoute
  '/modelo': typeof ModeloRoute
  '/origem': typeof OrigemRoute
  '/pacotes': typeof PacotesRoute
  '/proprietarios': typeof ProprietariosRoute
  '/turmas': typeof TurmasRoute
  '/utms': typeof UtmsRoute
  '/vendas': typeof VendasRoute
  '/admin/import': typeof AdminImportRoute
  '/app/workspaces': typeof AppWorkspacesRoute
  '/app/w/$wid/model': typeof AppWWidModelRoute
  '/app/w/$wid/sources': typeof AppWWidSourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditoria'
    | '/canais'
    | '/conta'
    | '/geografia'
    | '/login'
    | '/modelo'
    | '/origem'
    | '/pacotes'
    | '/proprietarios'
    | '/turmas'
    | '/utms'
    | '/vendas'
    | '/admin/import'
    | '/app/workspaces'
    | '/app/w/$wid/model'
    | '/app/w/$wid/sources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auditoria'
    | '/canais'
    | '/conta'
    | '/geografia'
    | '/login'
    | '/modelo'
    | '/origem'
    | '/pacotes'
    | '/proprietarios'
    | '/turmas'
    | '/utms'
    | '/vendas'
    | '/admin/import'
    | '/app/workspaces'
    | '/app/w/$wid/model'
    | '/app/w/$wid/sources'
  id:
    | '__root__'
    | '/'
    | '/auditoria'
    | '/canais'
    | '/conta'
    | '/geografia'
    | '/login'
    | '/modelo'
    | '/origem'
    | '/pacotes'
    | '/proprietarios'
    | '/turmas'
    | '/utms'
    | '/vendas'
    | '/admin/import'
    | '/app/workspaces'
    | '/app/w/$wid/model'
    | '/app/w/$wid/sources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditoriaRoute: typeof AuditoriaRoute
  CanaisRoute: typeof CanaisRoute
  ContaRoute: typeof ContaRoute
  GeografiaRoute: typeof GeografiaRoute
  LoginRoute: typeof LoginRoute
  ModeloRoute: typeof ModeloRoute
  OrigemRoute: typeof OrigemRoute
  PacotesRoute: typeof PacotesRoute
  ProprietariosRoute: typeof ProprietariosRoute
  TurmasRoute: typeof TurmasRoute
  UtmsRoute: typeof UtmsRoute
  VendasRoute: typeof VendasRoute
  AdminImportRoute: typeof AdminImportRoute
  AppWorkspacesRoute: typeof AppWorkspacesRoute
  AppWWidModelRoute: typeof AppWWidModelRoute
  AppWWidSourcesRoute: typeof AppWWidSourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utms': {
      id: '/utms'
      path: '/utms'
      fullPath: '/utms'
      preLoaderRoute: typeof UtmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turmas': {
      id: '/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof TurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proprietarios': {
      id: '/proprietarios'
      path: '/proprietarios'
      fullPath: '/proprietarios'
      preLoaderRoute: typeof ProprietariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacotes': {
      id: '/pacotes'
      path: '/pacotes'
      fullPath: '/pacotes'
      preLoaderRoute: typeof PacotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/origem': {
      id: '/origem'
      path: '/origem'
      fullPath: '/origem'
      preLoaderRoute: typeof OrigemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelo': {
      id: '/modelo'
      path: '/modelo'
      fullPath: '/modelo'
      preLoaderRoute: typeof ModeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geografia': {
      id: '/geografia'
      path: '/geografia'
      fullPath: '/geografia'
      preLoaderRoute: typeof GeografiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canais': {
      id: '/canais'
      path: '/canais'
      fullPath: '/canais'
      preLoaderRoute: typeof CanaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditoria': {
      id: '/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuditoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workspaces': {
      id: '/app/workspaces'
      path: '/app/workspaces'
      fullPath: '/app/workspaces'
      preLoaderRoute: typeof AppWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/w/$wid/sources': {
      id: '/app/w/$wid/sources'
      path: '/app/w/$wid/sources'
      fullPath: '/app/w/$wid/sources'
      preLoaderRoute: typeof AppWWidSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/w/$wid/model': {
      id: '/app/w/$wid/model'
      path: '/app/w/$wid/model'
      fullPath: '/app/w/$wid/model'
      preLoaderRoute: typeof AppWWidModelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditoriaRoute: AuditoriaRoute,
  CanaisRoute: CanaisRoute,
  ContaRoute: ContaRoute,
  GeografiaRoute: GeografiaRoute,
  LoginRoute: LoginRoute,
  ModeloRoute: ModeloRoute,
  OrigemRoute: OrigemRoute,
  PacotesRoute: PacotesRoute,
  ProprietariosRoute: ProprietariosRoute,
  TurmasRoute: TurmasRoute,
  UtmsRoute: UtmsRoute,
  VendasRoute: VendasRoute,
  AdminImportRoute: AdminImportRoute,
  AppWorkspacesRoute: AppWorkspacesRoute,
  AppWWidModelRoute: AppWWidModelRoute,
  AppWWidSourcesRoute: AppWWidSourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
